# Form implementation generated from reading ui file '/media/miles/Commun/Studi/0_2_Evaluations/ECF/PARADOX-EG/desktop/gui/loginwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.frameLogo = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLogo.sizePolicy().hasHeightForWidth())
        self.frameLogo.setSizePolicy(sizePolicy)
        self.frameLogo.setObjectName("frameLogo")
        self.verticalLayout.addWidget(self.frameLogo)
        self.editUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.editUsername.setObjectName("editUsername")
        self.verticalLayout.addWidget(self.editUsername)
        self.editPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.editPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.editPassword.setObjectName("editPassword")
        self.verticalLayout.addWidget(self.editPassword)
        self.buttonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonLogin.setObjectName("buttonLogin")
        self.verticalLayout.addWidget(self.buttonLogin)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Paradox Desktop"))
        self.labelTitle.setStyleSheet(_translate("LoginWindow", "QLabel { color: #b8b8b8; }"))
        self.labelTitle.setText(_translate("LoginWindow", "Paradox Desktop"))
        self.frameLogo.setStyleSheet(_translate("LoginWindow", "QFrame#frameLogo {\n"
"        background-image: url(./media/logo.png);\n"
"        background-repeat: no-repeat;\n"
"        background-position: center;\n"
"        }"))
        self.editUsername.setStyleSheet(_translate("LoginWindow", "QLineEdit {\n"
"        border: 1px solid #b8b8b8;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        background-color: #1e1e1e;\n"
"        color: #b8b8b8;\n"
"        }"))
        self.editPassword.setStyleSheet(_translate("LoginWindow", "QLineEdit {\n"
"        border: 1px solid #b8b8b8;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        background-color: #1e1e1e;\n"
"        color: #b8b8b8;\n"
"        }"))
        self.buttonLogin.setStyleSheet(_translate("LoginWindow", "QPushButton {\n"
"        background-color: #D27F35;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        padding: 8px 16px;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        }\n"
"        QPushButton:hover {\n"
"        background-color: #3A3238;\n"
"        }\n"
"        QPushButton:pressed {\n"
"        background-color: #161315;\n"
"        }"))
        self.buttonLogin.setText(_translate("LoginWindow", "Connexion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec())
