# Form implementation generated from reading ui file '/media/miles/Commun/Studi/0_2_Evaluations/ECF/PARADOX-EG/desktop/gui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 805)
        MainWindow.setStyleSheet("background-color: #1e1e1e;\n"
"                color: #b8b8b8;\n"
"                font-family: Arial;\n"
"            ")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelTitle.setFont(font)
        self.labelTitle.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        self.dateToday = QtWidgets.QDateEdit(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateToday.sizePolicy().hasHeightForWidth())
        self.dateToday.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.dateToday.setFont(font)
        self.dateToday.setObjectName("dateToday")
        self.horizontalLayout.addWidget(self.dateToday)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelLegend = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelLegend.setFont(font)
        self.labelLegend.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelLegend.setObjectName("labelLegend")
        self.horizontalLayout_2.addWidget(self.labelLegend)
        self.labelTocome = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelTocome.setFont(font)
        self.labelTocome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTocome.setObjectName("labelTocome")
        self.horizontalLayout_2.addWidget(self.labelTocome)
        self.labelStarted = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelStarted.setFont(font)
        self.labelStarted.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStarted.setObjectName("labelStarted")
        self.horizontalLayout_2.addWidget(self.labelStarted)
        self.labelSoon = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelSoon.setFont(font)
        self.labelSoon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSoon.setObjectName("labelSoon")
        self.horizontalLayout_2.addWidget(self.labelSoon)
        self.labelFinished = QtWidgets.QLabel(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelFinished.setFont(font)
        self.labelFinished.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelFinished.setObjectName("labelFinished")
        self.horizontalLayout_2.addWidget(self.labelFinished)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.bookingList = QtWidgets.QListWidget(parent=MainWindow)
        self.bookingList.setStyleSheet("background-color: #1e1e1e;\n"
"                            color: #b8b8b8;\n"
"                            font-family: Arial;\n"
"                            selection-background-color: #3A3238;\n"
"                            selection-color: #b8b8b8;\n"
"                        ")
        self.bookingList.setObjectName("bookingList")
        self.verticalLayout.addWidget(self.bookingList)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Booking List"))
        self.labelTitle.setText(_translate("MainWindow", "Liste des réservations pour la date du jour :"))
        self.labelLegend.setText(_translate("MainWindow", "Légende :"))
        self.labelTocome.setText(_translate("MainWindow", "Parties à venir"))
        self.labelStarted.setText(_translate("MainWindow", "Parties en cours"))
        self.labelSoon.setText(_translate("MainWindow", "Parties temps restant < 5 minutes"))
        self.labelFinished.setText(_translate("MainWindow", "Parties terminées"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
